<a href="https://colab.research.google.com/github/Jeff-004/Projects/blob/main/Movie_Recommender_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing dependencies
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
movies = pd.read_csv("/content/drive/MyDrive/Datasets/movies.csv", on_bad_lines='skip')
movies.head()

Poster_Link  \
0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   
3  https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4  https://m.media-amazon.com/images/M/MV5BMWU4N2...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   
3    The Godfather: Part II          1974           A  202 min   
4              12 Angry Men          1957           U   96 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   
3          Crime, Drama          9.0   
4          Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   
3  The early life and career of Vito Corleone in ...        90.0   
4  A jury holdout attempts to prevent a miscarria...        96.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   
3  Francis Ford Coppola       Al Pacino  Robert De Niro  Robert Duvall   
4          Sidney Lumet     Henry Fonda     Lee J. Cobb  Martin Balsam   

            Star4  No_of_Votes        Gross  
0  William Sadler      2343110   28,341,469  
1    Diane Keaton      1620367  134,966,411  
2   Michael Caine      2303232  534,858,444  
3    Diane Keaton      1129952   57,300,000  
4    John Fiedler       689845    4,360,000

In [ ]:
movies.shape

(1000, 16)

In [ ]:
selected_features = ['Genre','Meta_score','Certificate', 'Star1', 'Star2','IMDB_Rating','Director', 'Series_Title']
print(selected_features)

['Genre', 'Meta_score', 'Certificate', 'Star1', 'Star2', 'IMDB_Rating', 'Director', 'Series_Title']


In [ ]:
for feature in selected_features:
    movies[feature] = movies[feature].fillna('')

In [ ]:
#combining all the features

combined_features = (
    movies['Genre'].astype(str) + ' ' +
    movies['Meta_score'].astype(str) + ' ' +
    movies['Certificate'].astype(str) + ' ' +
    movies['Star1'].astype(str) + ' ' +
    movies['Star2'].astype(str) + ' ' +
    movies['Director'].astype(str) + ' ' +
    movies['Series_Title'].astype(str)
)
print(combined_features)

0      Drama 80.0 A Tim Robbins Morgan Freeman Frank ...
1      Crime, Drama 100.0 A Marlon Brando Al Pacino F...
2      Action, Crime, Drama 84.0 UA Christian Bale He...
3      Crime, Drama 90.0 A Al Pacino Robert De Niro F...
4      Crime, Drama 96.0 U Henry Fonda Lee J. Cobb Si...
                             ...                        
995    Comedy, Drama, Romance 76.0 A Audrey Hepburn G...
996    Drama, Western 84.0 G Elizabeth Taylor Rock Hu...
997    Drama, Romance, War 85.0 Passed Burt Lancaster...
998    Drama, War 78.0  Tallulah Bankhead John Hodiak...
999    Crime, Mystery, Thriller 93.0  Robert Donat Ma...
Length: 1000, dtype: object


In [ ]:
#converting text into numbers

vectorizer = TfidfVectorizer()

featured_vector = vectorizer.fit_transform(combined_features)
print(featured_vector)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 12552 stored elements and shape (1000, 4304)>
  Coords	Values
  (0, 1094)	0.06931133208802676
  (0, 59)	0.23983883481901674
  (0, 3828)	0.28424235267179876
  (0, 3233)	0.3568925377968593
  (0, 2658)	0.3418162622186342
  (0, 1382)	0.32056744523432906
  (0, 1368)	0.28424235267179876
  (0, 933)	0.3568925377968593
  (0, 3801)	0.12552953010835474
  (0, 3471)	0.37814135478116445
  (0, 3160)	0.37814135478116445
  (1, 1094)	0.07496748275382421
  (1, 3801)	0.13577336634566556
  (1, 877)	0.14520088936486503
  (1, 1)	0.30290091669361774
  (1, 2468)	0.35706181323869746
  (1, 537)	0.35706181323869746
  (1, 141)	0.29478958529275356
  (1, 2898)	0.2987002823277278
  (1, 1366)	0.3304207739587761
  (1, 1351)	0.2681485460128322
  (1, 846)	0.3379896837600078
  (1, 1511)	0.3697101753910562
  (2, 1094)	0.07281376558232
  (2, 3801)	0.13187277611920933
  :	:
  (997, 1711)	0.32387551511465096
  (997, 1228)	0.32387551511465096
  (998, 1094)	0.0745695

In [ ]:
#obtaining the similarity matrix

similarity = cosine_similarity(featured_vector)
print(similarity)

[[1.         0.02223966 0.02160075 ... 0.00411465 0.00516851 0.01556457]
 [0.02223966 1.         0.04384108 ... 0.00445042 0.00559029 0.03608846]
 [0.02160075 0.04384108 1.         ... 0.00432257 0.00542969 0.03505168]
 ...
 [0.00411465 0.00445042 0.00432257 ... 1.         0.0425921  0.        ]
 [0.00516851 0.00559029 0.00542969 ... 0.0425921  1.         0.15593019]
 [0.01556457 0.03608846 0.03505168 ... 0.         0.15593019 1.        ]]


In [ ]:
#getting input from the user

movie_name = input("Enter your Favourite movie: ")

Enter your Favourite movie: Godfather


In [ ]:
#creating the list of all movie titles

list_of_movies = movies['Series_Title'].tolist()

In [ ]:
#finding the closest match for the movie inputed

find_close_match = difflib.get_close_matches(movie_name,list_of_movies)
# Print result
if find_close_match:
    close_match = find_close_match[0]
    print("Best match found:", close_match)
else:
    print("No close match found.")

Best match found: The Godfather


In [ ]:
if find_close_match:
    index = movies[movies['Series_Title'] == close_match].index[0]
    print("Index of the movie:", index)

Index of the movie: 1


In [ ]:
#getting the similarity list of the movie

similar_list = list(enumerate(similarity[index]))
print(similar_list)

[(0, np.float64(0.022239662971554632)), (1, np.float64(1.0000000000000002)), (2, np.float64(0.04384107830335568)), (3, np.float64(0.6061208580244626)), (4, np.float64(0.024467961530824207)), (5, np.float64(0.059730727101695254)), (6, np.float64(0.02538365297381633)), (7, np.float64(0.005031832346859463)), (8, np.float64(0.0)), (9, np.float64(0.005717439614127184)), (10, np.float64(0.05846517026351691)), (11, np.float64(0.005615164213801546)), (12, np.float64(0.0)), (13, np.float64(0.04880358363914086)), (14, np.float64(0.014208908157203751)), (15, np.float64(0.027597288224914168)), (16, np.float64(0.06806352051767815)), (17, np.float64(0.018430219089666338)), (18, np.float64(0.004672727105883763)), (19, np.float64(0.0044103961358945894)), (20, np.float64(0.005680925113415512)), (21, np.float64(0.005475868639866741)), (22, np.float64(0.02197091896790174)), (23, np.float64(0.0)), (24, np.float64(0.0054126648637491045)), (25, np.float64(0.040638345431744334)), (26, np.float64(0.0037630685

In [ ]:
#sorting the sim_list in decreasing order

sorted_similar_list = sorted(similar_list, key = lambda x:x[1], reverse = True)
print(sorted_similar_list)

[(1, np.float64(1.0000000000000002)), (3, np.float64(0.6061208580244626)), (974, np.float64(0.5820751756113213)), (74, np.float64(0.49783040541525003)), (693, np.float64(0.3156499204658215)), (305, np.float64(0.2695818605756022)), (484, np.float64(0.2385846235697268)), (164, np.float64(0.22507383298088285)), (447, np.float64(0.21954133028937042)), (849, np.float64(0.21150603359403447)), (649, np.float64(0.21144305150768697)), (108, np.float64(0.20281500998122953)), (809, np.float64(0.1975285101774514)), (416, np.float64(0.1908056398161994)), (523, np.float64(0.19005334565085147)), (823, np.float64(0.18410004383140963)), (398, np.float64(0.16785006179841877)), (663, np.float64(0.11767323040194982)), (780, np.float64(0.10636015416090391)), (721, np.float64(0.10165424083090603)), (50, np.float64(0.09782608251547023)), (491, np.float64(0.09591025804634604)), (871, np.float64(0.09537837486542901)), (119, np.float64(0.09481386684668341)), (559, np.float64(0.09473285798715862)), (553, np.floa

In [ ]:
#printing the top 10 similar movies
print("Top 10 Movies for You: \n")

i=1
for movie in sorted_similar_list:
  ind = movie[0]
  title_name = movies[movies.index==ind]['Series_Title'].values[0]
  if i<=10:
    print(i,'.',title_name)
    i+=1

Top 10 Movies for You: 

1 . The Godfather
2 . The Godfather: Part II
3 . The Godfather: Part III
4 . Apocalypse Now
5 . The Conversation
6 . On the Waterfront
7 . The Irishman
8 . Heat
9 . A Streetcar Named Desire
10 . Serpico
